services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
     - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: {your_username}
      POSTGRES_PASSWORD: {your_password}
      POSTGRES_DB: {your_db_name}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes: 
      - cache:/data
  
volumes: 
  timescaledb-data:
  cache: 
    driver: local
